---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
data:
  # hydra settings
  global.ory.hydra.persistence.postgresql.enabled: "false"
  global.ory.hydra.persistence.gcloud.enabled: "true"
  # gcloud sql proxy settings
  gcloud-sqlproxy.cloudsql.instance.instanceName: "hydra-persistence-demo"
  gcloud-sqlproxy.cloudsql.instance.project: "sap-se-cx-kyma-goat"
  gcloud-sqlproxy.cloudsql.instance.region: "europe-north1-b"
  gcloud-sqlproxy.cloudsql.instance.port: "5432"
  # gcloud db settings
  global.ory.hydra.persistence.user: "hydra"
  global.ory.hydra.persistence.dbUrl: "ory-gcloud-sqlproxy.kyma-system"
  global.ory.hydra.persistence.dbName: "db4hydra"
  global.ory.hydra.persistence.dbType: "postgres"
  # Oathkeeper: autoscaling and allocated resources
  oathkeeper.deployment.resources.limits.cpu: "800m"
  oathkeeper.deployment.resources.requests.cpu: "200m"
  hpa.oathkeeper.minReplicas: "3"
  hpa.oathkeeper.maxReplicas: "10"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
  name: ory-overrides-secrets
  namespace: kyma-installer
type: Opaque
data:
  # hydra settings
  # hydra.hydra.config.secrets.system: custom signing key, base64 encdoded
  hydra.hydra.config.secrets.system: R1dHTnJ3bUlkN3FZbkNyRA==
  # hydra.hydra.config.secrets.cookie: custom signing key, base64 encdoded
  hydra.hydra.config.secrets.cookie: R1dHTnJ3bUlkN3FZbkNyRA==
  # global.ory.hydra.persistence.gcloud.saJson: ServiceAccount json file from GCloud, base64 encoded
  global.ory.hydra.persistence.gcloud.saJson: "YmFzZTY0X2VuY29kZWRfc2VydmljZV9hY2NvdW50X2pzb24="
  # global.ory.hydra.persistence.password: password, base64 encdoded
  global.ory.hydra.persistence.password: RHUyMmc0MmhtbEp2anhjbg==
